version: "3"
services:

    client_mobile:
        image: mobile
        build: ./client_mobile
        ports:
        - "8081:8081"
        environment:
            - PORT=80
            - DB_NAME=db
            - DB_PORT=27017

