version: "3.3"
services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - "8080:8080"
        command: npm start server/
        image: area2019
        container_name: server_area
        ports:
            - "8080:8080"
        # volumes:
        #     - ./server/:/usr/src/app/
        restart: always
        depends_on:
            - db
        links:
            - db:db

    client:
        build: ./web-client/.
        ports:
            - "8081:8080"
        container_name: client_web_area
        volumes:
            - ./web-client/:/usr/src/app/
        links:
            - server:server
    db:
        image: mongo
        ports:
            - "27017:27017"