version: "3.3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm start
    image: area2019
    container_name: DEV_area_2019
