version: "3.3"
services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - "8080:8080"
        command: npm start server/
        image: area2019
        container_name: server_area
        volumes:
            - ./server/:/usr/src/app/:ro
        restart: always
        depends_on:
            - db
        links:
            - db:db

    mobile_client:
        build: ./client_mobile
        depends_on:
            - server
        ports:
        - "8081:8081"
        container_name: client_web_area
        volumes:
            - ./clients/:/client_mobile/app/build/outputs/apk/release/:ro 
        environment:
            - PORT=81
            - DB_NAME=db
            - DB_PORT=27017y

    web_client:
        build: ./web-client/.
        depends_on:
            - server
            - mobile_client
        ports:
            - "8081:8081"
        container_name: client_web_area
        volumes:
            - ./clients/:/usr/src/:ro
        links:
            - server:server

    db:
        image: mongo
        ports:
            - "27017:27017"

volumes:
    server:
    clients: