version: "3.3"
services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - "8080:8080"
        command: npm start server/
        image: area2019
        container_name: server_area
        restart: always
        depends_on:
            - db
        links:
            - db:db
        environment:
            - GITHUB_ID=a5c1a4e56df11fc5735a
            - GITHUB_SECRET=d34b0ddb1e2990542e7c42ea6faa1f668a5d8e20
            - NGROK_TOKEN=1XKuDgkqMYnETxr5sEgd6faCkh1_3iQ2dASUNn2DVmr8dbi5R
            - DISCORD_ID=680706257992024065
            - DISCORD_SECRET=eaQjWT9RwgohzOrn2JRgZRwBxhtxVBZ5
            - SLACK_ID=933637704274.945976210260
            - SLACK_SECRET=248197e37352e5aa521b969a3cbb8a91
            - REDDIT_ID=xxa4cp-hsWE_iA
            - REDDIT_SECRET=466F9UWdI-Eh1iz7AhN8zNyszE8
            - TWITCH_ID=5cfjsk5flx3vkouomr7a26y7usrxmz

    mobile_client:
        image: mobile_client
        build: ./client_mobile
        depends_on:
            - server
        container_name: client_mobile_area
        volumes:
            - clients:/client_mobile/app/build/outputs/apk/:rw
        links:
            - server:server

    web_client:
        build: ./web-client
        depends_on:
            - server
            - mobile_client
        ports:
            - "8081:8081"
        container_name: client_web_area
        volumes:
            - clients:/web-client/public/app/:ro
        links:
            - server:server

    db:
        image: mongo
        ports:
            - "27017:27017"

volumes:
    server:
    clients: